const dataLocation = [
  {
    title: "WPC - CenturyOn West Point - Q.Tây Hồ",
    name: "WEST POINT - QUẬN TÂY HỒ",
    city: "Hà Nội",
    district: "Q. Tây Hồ",
    ward: "P.Quảng An",
    street: "Tầng 2 & 3 , Somerset West Point, Số 2 Tây Hồ",
    desc: [
      "Nhờ đáp ứng được mọi nhu cầu luyện tập theo tiêu chuẩn 5 sao với thiết kế cực kỳ sang trọng trong từng chi tiết nhỏ, phòng tập gym California Centuryon Somerset West Point đã trở thành địa điểm check-in quen thuộc của giới thượng lưu Hà Nội.",
      "Sang trọng, đẳng cấp, tinh tế trong từng chi tiết đó chính là những trải nghiệm tuyệt vời chỉ có khi bạn bước chân vào CLB California Centuryon West Point quận Tây Hồ. Một nơi tập luyện đạt chuẩn quốc tế cùng với các tiện ích phục hồi năng lượng tích hợp, đặc biệt có hồ bơi thư giãn chắc chắn sẽ mang lại cho bạn những trải nghiệm chưa từng có. Khám phá ngay hôm nay!",
      "Tọa lạc tại Somerset West Point - khu vực trung tâm phía Bắc Hà Nội, California Centuryon quận Tây Hồ vượt xa định nghĩa của một trung tâm thể hình thông thường mà còn là phong cách sống. Đây là phòng tập thuộc chuỗi phòng tập cao cấp bậc nhất tại California dành cho giới thượng lưu tại Việt Nam. ",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Chủ nhật",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/Hanoi_900x600.jpg",
      "https://cali.vn/storage/app/media/old/club/qu%E1%BA%ADn%204/Facilties_1.png",
      "https://cali.vn/storage/app/media/old/club/qu%E1%BA%ADn%204/TNL-Plaza-Facilties_2.png",
      "https://cali.vn/storage/app/media/old/club/qu%E1%BA%ADn%204/TNL-Plaza-Facilties_3.jpg",
    ],
    phone: "(024) 7300 1777",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Lồng MMA",
      "Phòng trang điểm",
      "Phòng thay đồ",
      "Pilates Studio",
    ],
  },
  {
    title: "VSC - Vincom star city - Q.Cầu Giấy",
    name: "VINCOM STAR CITY - QUẬN CẦU GIẤY",
    city: "Hà Nội",
    ward: "P. Trung Hòa",
    district: "Q. Cầu Giấy",
    street:
      "Tầng 3, Trung tâm thương mại Vincom Star City, 119 đường Trần Duy Hưng",
    desc: [
      "Là một ngôi sao mới của chuỗi câu lạc bộ thể hình hàng đầu California Fitness & Yoga, phòng tập Vincom Star City được thiết kế theo chuẩn quốc tế với nhiều chương trình tập luyện đa dạng từ các chuyên gia hàng đầu của lĩnh vực thể hình trong khu vực.",
      "Gây ấn tượng với thiết kế không gian kiến trúc thoáng đãng và sang trọng, California Fitness & Yoga Vincom Star quận Cầu Giấy chính là lựa chọn hoàn hảo dành cho sức khoẻ của bạn. Tận hưởng các dịch vụ tập luyện hiện đại bậc nhất ngay hôm nay!",
      "Toạ lạc tại tầng 3 TTTM Vincom Star City, California Fitness & Yoga Vincom quận Cầu Giấy chính là một trong những phòng tập gym có quy mô rộng lớn nhất Hà Nội. Với không gian thiết kế khoa học theo tiêu chuẩn quốc tế: phòng tập Yoga yên tĩnh, studio Dance/GroupX với chất lượng âm thanh 5 sao, khu vực gym với trang thiết bị nhập khẩu hoàn toàn từ Technogym và các tiện ích thư giãn 5 sao được tích hợp ngay trong khu vực tập luyện như phòng xông hơi, phòng tắm, tủ đồ rộng thoáng,...Tất cả sẽ truyền cảm hứng cho bạn thuận tiện duy trì lối sống khoẻ mạnh.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "6:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Hanoi_VSC_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Facilities/VSC_1900x600_2.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Facilities/VSC_1900x600_3.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Facilities/VSC_1900x600_4.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Facilities/VSC_1900x600_5.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Facilities/VSC_1900x600_6.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Facilities/VSC_1900x600_1.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Facilities/VSC_1900x600_7.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Facilities/VSC_1900x600_8.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/VSC/Facilities/VSC_1900x600_9.jpg",
    ],
    phone: "(024) 7300 1277",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "TCM - Times City - Q.Hai Bà Trưng",
    name: "TIMES CITY - QUẬN HAI BÀ TRƯNG",
    city: "Hà Nội",
    ward: "P. Vĩnh Tuy",
    district: "Q. Hai Bà Trưng",
    street: "Time City Megamall, Tòa nhà T18, 458 Minh Khai",
    desc: [
      "Nằm giữa lòng khu đô thị Times City, trung tâm California Fitness and Yoga quận Hai Bà Trưng chiếm trọn trái tim của các hội viên với hệ thống thiết bị chuẩn quốc tế cùng nhiều chương trình tập luyện hiện đại như Yoga, Dance, Group X, và nhiều bộ môn tập luyện khác.",
      "Vượt qua mọi trở ngại khiến bạn mất động lực khi tập luyện. Trải nghiệm ngay California Fitness & Yoga quận Hai Bà Trưng - cộng đồng yêu thích lối sống năng động và khoẻ mạnh lớn nhất tại Hà Nội. Với trang thiết bị đầy đủ cùng với chương trình tập luyện đa dạng và các tiện ích phục hồi năng lượng tiêu chuẩn 5 sao như hồ bơi trong nhà, bạn sẽ luôn được truyền cảm hứng để duy trì lối sống lành mạnh.",
      "Tọa lạc tại khu đô thị sầm uất Times City, California Fitness & Yoga quận Hai Bà Trưng là một trong những cơ sở được đầu tư lớn về không gian, trang thiết bị và các chương trình luyện tập đa dạng bậc nhất trong hệ thống. Bên cạnh các lớp học Dance, Yoga, GroupX, bạn còn có thể tham gia KickFit/ MMA.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "6:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/TCM/1P4A1446.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/TCM/1P4A1563.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/TCM/1P4A1552.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/TCM/1P4A1529.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/TCM/1P4A1489.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/TCM/1P4A1608.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/TCM/1P4A1423.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/TCM/1P4A1553.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/TCM/1P4A1492.jpg",
    ],
    phone: "(024) 7107 9999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "CPT - Capital Building - Q.Hoàn Kiếm",
    name: "CAPITAL TOWER - QUẬN HOÀN KIẾM",
    city: "Hà Nội",
    ward: "P. Trần Hưng Đạo",
    district: "Q. Hoàn Kiếm",
    street: "Tầng 2, Capital Building, 41 Hai Bà Trưng",
    desc: [
      "Phòng tập tại Quận Hoàn Kiếm được thiết kế theo chuẩn phòng tập quốc tế với những khu vực tập luyện chuyên biệt. Dưới sự hướng dẫn của các huấn luyện viên đạt chuẩn NASM cùng nhiều tiện ích mở rộng như hồ Jacuzzi massage, phòng xông hơi sauna giúp quý hội viên phục hồi năng lượng sau mỗi giờ tập.",
      "Nổi bật nhất giữa các phòng tập tại thành phố Hà Nội, California Fitness & Yoga quận Hoàn Kiếm tự hào được đầu tư trang thiết bị hiện đại bậc nhất và sở hữu không gian tập luyện đặc biệt truyền cảm hứng. Với các tiện ích tích hợp ngay tại phòng tập như phòng xông hơi, quầy bar dinh dưỡng cùng với chương trình luyện tập đa dạng sẽ mang lại những trải nghiệm khác biệt dành cho bạn. Khám phá ngay hôm nay!",
      "Toạ lạc tại tầng 2 toà nhà Capital Building - vị trí đắc địa ngay đường huyết mạch của thủ đô, California quận Hoàn Kiếm hội tụ đầy đủ các chuẩn mực thượng lưu từ thiết kế sang trọng, thiết bị đẳng cấp, chương trình tập luyện đa dạng tiêu chuẩn quốc tế,...Tất cả sẽ đáp ứng vượt bậc nhu cầu chăm sóc sức khoẻ và giải trí của khách hàng.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "6:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/CPT/California-08194.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/CPT/California-08213.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/CPT/California-08237.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/CPT/California-08266.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/CPT/California-08311.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/CPT/California-08461.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/CPT/California-08442.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/CPT/California-08339.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/CPT/California-08319.jpg",
    ],
    phone: "(024) 7106 9899",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "SCT - Sky City Tower - Q.Đống Đa",
    name: "SKY CITY TOWER - QUẬN ĐỐNG ĐA",
    city: "Hà Nội",
    ward: "P. Láng Hạ",
    district: "Q. Đống Đa",
    street: "Sky City, Tầng M, 88 Láng Hạ",
    desc: [
      "Không chỉ có lịch học trải đều các khung giờ, Trung tâm California Fitness and Yoga Quận Đống Đa còn sở hữu khu vực Hydro – Therapy hệ thống phòng tắm hơi lớn nhất Việt Nam, cung cấp không gian thư giãn sau tập luyện độc đáo khó nơi nào sánh được.",
      "Là một trong số những phòng tập đặc biệt của hệ thống California sở hữu khu vực phòng tắm hơi Hydro-therapy lớn nhất Việt Nam, California quận Đống Đa với các trải nghiệm thượng lưu chắc chắn sẽ là địa điểm lý tưởng dành cho việc rèn luyện sức khoẻ mà bạn không nên bỏ lỡ. Khám phá ngay!",
      "Toạ lạc tại tầng M Sky City, California quận Đống Đa được biết đến là một trong những trung tâm Fitness theo tiêu chuẩn quốc tế đầu tiên tại Hà Nội. Với trang thiết bị đạt tiêu chuẩn Mỹ và Châu u cùng với đội ngũ HLV kinh nghiệm, bạn có thể dễ dàng đạt được mọi mục tiêu từ giảm cân, tăng cơ, sở hữu vóc dáng và sức khoẻ mong muốn nhanh chóng. Hơn nữa, bạn có thể trải nghiệm không giới hạn các tiện ích phục hồi năng lượng như phòng xông hơi, lounge thư giãn khi trở thành hội viên ngay hôm nay.",
    ],
    times_days: [
      {
        time: "5:45 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "5:45 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/SCT/California-07549.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/SCT/California-07605.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/SCT/California-08170.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/SCT/California-07903.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/SCT/California-07896.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/SCT/California-07810.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/SCT/California-08149.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/SCT/California-07754.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/SCT/California-07987.jpg",
    ],
    phone: "(024) 7106 9899",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "RCC - CenturyOn Royal City - Q.Thanh Xuân",
    name: "ROYAL CITY - QUẬN THANH XUÂN",
    city: "Hà Nội",
    ward: "",
    district: "Q. Thanh Xuân",
    ward: "P. Thượng Đình",
    street: "Tầng 2, R3, Royal City, Mega Vincom, 72A Nguyễn Trãi",
    desc: [
      "Phòng tập gym California Centuryon quận Thanh Xuân là một trong những siêu câu lạc bộ đầu tiên dành riêng cho giới thượng lưu Hà Nội với cơ sở hạ tầng được chăm chút tỉ mỉ trong từng đường nét cùng với trang thiết bị cao cấp 5 sao phục vụ cho những hội viên VIP.",
      "Một không gian đẳng cấp với các dịch vụ “thảm đỏ” như đặt trước lịch tập luyện, được chuẩn bị khăn và áo choàng VIP, được dẫn theo bạn bè và người thân cùng tham gia tập luyện,...Tất cả chính là đặc quyền dành cho bạn khi trở thành hội viên Centuryon tại California Centuryon Royal City. Khám phá ngay!",
      "Tọa lạc tại tầng 2 khu TTTM Mega Vincom, California Centuryon Royal City chính là một trong 4 địa điểm được Business Insider bình chọn là phòng tập có giá đắt đỏ nhất châu Á. Chính bởi độ xa hoa trong không gian thiết kế đậm chất Hoàng Gia cùng với các dịch vụ tập luyện tiêu chuẩn 5 sao. Đây chính là lựa chọn hoàn hảo để rèn luyện sức khoẻ được hàng loạt doanh nhân và siêu sao nổi tiếng tin cậy.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Chủ nhật",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/HN_RCC_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_01.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_02.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_03.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_04.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_05.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_06.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_07.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_08.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_09.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/RCC/Facility%20Slider/RCC_slider_1900x_10.jpg",
    ],
    phone: "(024) 7307 7555",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "HDC - Hàng Da Gallery - Q.Hoàn Kiếm",
    name: "HÀNG DA PLAZA - QUẬN HOÀN KIẾM",
    city: "Hà Nội",
    ward: "",
    district: "Q. Hoàn Kiếm",
    street: "Tầng 4-5 TTTM Hàng Da Plaza, Số 1 Hàng Da",
    desc: [
      "Thuộc khuôn viên của Hàng Da Plaza đông đúc, Trung tâm thể hình và Yoga của California mang đến những trải nghiệm cao cấp cho các hội viên bằng những tiện ích chăm sóc sức khỏe đẳng cấp cùng hàng trăm lớp học thể dục theo nhóm GroupX - Yoga mỗi tuần.",
      "Vượt khỏi tiêu chuẩn của một phòng tập thông thường, California Hàng Da chính là mô hình tích hợp độc đáo giữa tập luyện và phục hồi năng lượng ngay tại Thủ Đô. Từng chi tiết trong không gian tập luyện được thiết kế và hoàn thiện theo tiêu chuẩn cao cấp và được chăm chút cẩn trọng để đảm bảo an toàn cho sức khoẻ của quý hội viên. Khám phá ngay hôm nay!",
      "Tọa lạc tại vị trí khu phức hợp trung tâm thương mại Hàng Da Plaza, California Hàng Da được trang bị đầy đủ hệ thống máy tập hiện đại và đa dạng nhằm đáp ứng tốt nhất mọi nhu cầu chăm sóc sức khoẻ của quý hội viên. Nơi đây có các khu tập luyện riêng biệt như cardio, phòng giãn cơ, studio yoga, phòng tập dance, lớp tập nhóm GroupX,....với hơn 100 lớp học mỗi tuần chắc chắn sẽ mang lại cho các hội viên những giờ tập luyện vui vẻ và thoải mái.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "6:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Hanoi_HDC_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Facilities/HDC_1900x600_1.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Facilities/HDC_1900x600_2.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Facilities/HDC_1900x600_3.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Facilities/HDC_1900x600_4.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Facilities/HDC_1900x600_5.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Facilities/HDC_1900x600_6.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Facilities/HDC_1900x600_7.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Facilities/HDC_1900x600_8.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDC/Facilities/HDC_1900x600_9.jpg",
    ],
    phone: "(024) 7109 7889",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
      "Pilates Studio",
    ],
  },
  {
    title: "PCH - PICO Xuân Thủy - Q.Cầu Giấy",
    name: "PICO XUÂN THỦY - QUẬN CẦU GIẤY",
    city: "Hà Nội",
    ward: "",
    district: "Q. Cầu Giấy",
    street:
      "Tầng 3 & 4, Tòa nhà Long Giang, Trung tâm điện máy Pico, 173 Xuân Thủy",
    desc: [
      "Nổi bật trên mặt tiền con đường nhộn nhịp Xuân Thủy, California Fitness & Yoga Quận Cầu Giấy chính là điểm đến yêu thích của các nhóm bạn nhờ vào các lớp thể dục nhóm GroupX mở thường xuyên và cửa hàng thời trang thể thao Ca Republik thời thượng.",
      "Không gì có thể duy trì động lực tốt bằng việc chọn lựa được môi trường tập luyện lý tưởng. Đến với California quận Cầu Giấy - phòng tập đẳng cấp 5 sao, bạn không chỉ thả ga tập luyện không giới hạn các lớp dance, yoga, gym đến các lớp tập nhóm Group X sôi động mà còn được thư giãn phục hồi năng lượng với các dịch vụ tiện ích cao cấKhám phá ngay hôm nay!",
      "Toạ lạc tại vị trí trung tâm tầng 3, 4 toà nhà Long Giang, California Fitness & Yoga quận Cầu Giấy thu hút những người đam mê thay đổi hình thể bởi không gian và hệ thống máy tập đạt chuẩn quốc tế nhập khẩu hoàn toàn từ thương hiệu nổi tiếng Technogym. Cùng với đó là hệ thống lọc không khí và các tiện nghi thư giãn như phòng xông hơi, phòng tắm và quầy thức uống dinh dưỡng chắc chắn sẽ đem lại cho quý hội viên cảm giác an toàn và thoải mái như đang ở nhà.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "6:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/HN_PHC_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_1.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_2.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_3.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_4.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_5.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_6.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_7.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_8.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_9.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_10.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_11.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/PHC/Slider/PHC_slider_1900x800px_12.jpg",
    ],
    phone: "(024) 7309 4999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "HDY - Handico Tower - Q.Nam Từ Liêm",
    name: "HANDICO TOWER - QUẬN NAM TỪ LIÊM",
    city: "Hà Nội",
    ward: "",
    district: "Q. Nam Từ Liêm",
    street: "Tầng 4 Handico Tower, Mễ Trì, Phố Phạm Hùng",
    desc: [
      "Phòng tập California Fitness & Yoga Handico Mễ Trì được thiết kế thoáng đãng, tạo ra một môi trường tĩnh lặng tuyệt đối để giúp hội viên đạt được hiệu quả tập luyện tốt nhất khi thử sức với các bộ môn Yoga mới lạ như: Yoga trên không, Yoga với bóng; Yoga trên mặt phẳng nghiêng độc quyền.",
      "Bạn yêu thích trải nghiệm Yoga chuyên sâu từ các lớp Yoga truyền thống đến các lớp Yoga thử thách với thảm bay và dụng cụ hỗ trợ? Trải nghiệm ngay các lớp Yoga giảm cân, đẹp da, thải độc,...độc đáo chỉ có tại California Fitness & Yoga Nam Từ Liêm.",
      "Ẩn mình bình yên tại tầng 4 toà nhà Handico Mễ Trì, California Fitness & Yoga quận Nam Từ Liêm chính là thiên đường Yoga đích thực dành cho các tín đồ đam mê bộ môn này. Bạn sẽ được tận hưởng không gian đậm chất thiền từ mùi trầm hương nhập khẩu từ Ấn Độ , hệ thống lọc khí khử trùng đến các lớp Yoga được thiết kế theo tiêu chuẩn Quốc Tế và chương trình Yoga nguyên bản bởi Yogi Ấn Độ giảng dạy. Đặc biệt, California Fitness & Yoga Nam Từ Liêm còn phục vụ trà thảo mộc miễn phí sau giờ học, hứa hẹn sẽ đem lại cho quý hội viên những trải nghiệm tập luyện khác biệt.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "6:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2023/Club/HDY/HDY-Thumbnail_900x600px.png",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDY/Facility%20Slider/HDY_slider_1900x800px_05.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDY/Facility%20Slider/HDY_slider_1900x800px_02.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDY/Facility%20Slider/HDY_slider_1900x800px_04.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDY/Facility%20Slider/HDY_slider_1900x800px_01.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDY/Facility%20Slider/HDY_slider_1900x800px_03.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDY/Facility%20Slider/HDY_slider_1900x800px_06.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDY/Facility%20Slider/HDY_slider_1900x800px_07.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/HDY/Facility%20Slider/HDY_slider_1900x800px_08.jpg",
    ],
    phone: "(024) 7309 3999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
      "Pilates Studio",
      "Yoga Intrinity",
    ],
  },
  {
    title: "MAC - Mac plaza - Q.Hà Đông",
    name: "MAC PLAZA - QUẬN HÀ ĐÔNG",
    city: "Hà Nội",
    ward: "P. Mộ Lao",
    district: "Q. Hà Đông",
    street: "Tầng 5-6, MAC Plaza, 10 Trần Phú",
    desc: [
      "Tọa lạc tại MAC Plaza là “tân binh” mới nhất trong chuỗi phòng Gym 5 sao của Trung tâm California. Trung tâm sở hữu trang thiết bị tập luyện mới nhất, tiên tiến nhập khẩu 100% từ Hoa Kỳ, hứa hẹn tiếp thêm động lực để quý hội viên có một sức khỏe bền bỉ và thể hình hoàn hảo.",
      "California Fitness & Yoga quận Hà Đông - một không gian xứng tầm dành cho những người yêu thích lối sống khoẻ mạnh. Vượt khỏi tiêu chuẩn của phòng tập thông thường, CLB tích hợp đầy đủ tiện ích hồi phục năng lượng cùng với chương trình luyện tập đa dạng sẽ chiều lòng ngay cả những vị khách khó tính nhất. Khám phá ngay!",
      "Toạ lạc tại tầng 5 & 6 TTTM Mac Plaza, phòng tập California quận Hà Đông là một trong những CLB mới nhất của chuỗi hệ thống phòng tập California. Không gian tập luyện với gam màu bạc trung tính được đầu tư trang thiết bị sang trọng, tích hợp các dịch vụ chăm sóc sức khoẻ cao cấp như phòng xông hơi, quầy thức uống dinh dưỡng Califresh,... vượt khỏi chuẩn phòng tập thông thường. California quận Hà Đông sẽ tiếp thêm động lực để quý hội viên hướng tới lối sống năng động, khoẻ mạnh.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "6:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Hanoi_MAC_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Facilities/MAC_1900x600_1.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Facilities/MAC_1900x600_2.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Facilities/MAC_1900x600_3.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Facilities/MAC_1900x600_4.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Facilities/MAC_1900x600_5.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Facilities/MAC_1900x600_6.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Facilities/MAC_1900x600_7.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Facilities/MAC_1900x600_8.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MAC/Facilities/MAC_1900x600_9.jpg",
    ],
    phone: "(024) 7306 4888",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "MPC - MIPEC Riverside - Q.Long Biên",
    name: "MIPEC RIVERSIDE - QUẬN LONG BIÊN",
    city: "Hà Nội",
    ward: "P. Ngọc Lâm",
    district: "Q. Long Biên",
    street: "Tầng 6 - Mipec Riverside, Số 2 phố Long Biên II",
    desc: [
      "California Fitness & Yoga Quận Long Biên sở hữu vị trí rất thuận tiện cho các hội viên ghé thăm, cùng những bài tập được thiết kế riêng theo nhu cầu và thể trạng riêng, chương trình huấn luyện viên cá nhân tại phòng tập dễ dàng chinh phục cả những hội viên khó tính nhất.",
      "California Fitness & Yoga quận Long Biên - một sự giao thoa giữa nét cổ kính và phong cách mới mẻ, nơi khách hàng có thể thoải mái tận hưởng những tiện nghi hiện đại bậc nhất ngay tại không gian tập luyện. Hãy khám phá ngay hôm nay!",
      "Toạ lạc tại tầng 6 TTTM Mipec - gần cạnh cây cầu lịch sử Long Biên, California Fitness & Yoga Long Biên với thiết kế sang trọng, thoáng đãng và sở hữu góc nhìn lý tưởng ra bờ sông chắc chắn sẽ là địa điểm tập luyện lý tưởng dành cho bạn. Dù cho nhu cầu của bạn là tăng cơ, giảm cân, tăng sức bền hay cải thiện sức khoẻ, chương trình tập luyện đa dạng cùng với tiện ích phục hồi năng lượng tích hợp sẽ giúp bạn nhanh chóng đạt được mục tiêu.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "6:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A6894.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A6900.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A6926.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A6951.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A6954.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A7006.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A7069.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A7116.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A7027.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A7030.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Hanoi/MPC/020A6979.jpg",
    ],
    phone: "(024) 7309 5999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "DNG - Tòa Nhà Bưu Điện Thành Phố - Q.Thanh Khê",
    name: "BƯU ĐIỆN THÀNH PHỐ - TP. ĐÀ NẴNG",
    city: "Đà Nẵng",
    ward: "P. Vĩnh Trung",
    district: "Q. Thanh Khê",
    street: "Tầng 3 Tòa Nhà Bưu Điện Thành Phố, 271 Nguyễn Văn Linh",
    desc: [
      "Với diện tích lên đến 5000m2, phòng tập California Fitness and yoga Đà Nẵng lọt top 1 những câu lạc bộ quy mô lớn bậc nhất tại Đà Nẵng, cộng hưởng cùng Thẩm mỹ viện Eri cùng thuộc tập đoàn FLG, phòng tập mang đến cho hội viên trải nghiệm một hệ sinh thái dịch vụ cao cấp chưa từng có.",
      "California Fitness & Yoga Đà Nẵng - trải nghiệm tập luyện, giải trí, kết nối mà bạn không nên bỏ lỡ khi đến thành phố biển xinh đẹp này. Với chương trình tập luyện đa dạng cùng với các tiện ích tích hợp như khu vực xông hơi thư giãn được nhập khẩu từ Thuỵ Điển sẽ giúp bạn đánh tan mệt mỏi sau những ngày làm việc căng thẳng. Khám phá ngay!",
      "Tọa lạc tại tòa nhà Bưu Điện của thành phố, California Fitness & Yoga Đà Nẵng chính là lựa chọn lý tưởng dành cho những người yêu thích lối sống khoẻ mạnh và năng động. Với diện tích rộng 5000m2 trải dài 4 tầng nhà, riêng khu vực tầng 3 là khu vực tập gym chuyên dụng với hơn 29+ máy chạy bộ cùng với máy tập phục vụ đủ các nhóm cơ nhập khẩu hoàn toàn từ Technogym, chắc chắn sẽ đem lại cho bạn trải nghiệm đầy đủ nhất về không gian tập luyện đẳng cấp quốc tế đích thực.",
    ],
    times_days: [
      {
        time: "5:00 - 22:00",
        day: "Thứ 2 - Chủ nhật",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/Danang_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/1P4A7978.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/1P4A7989.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/1P4A8104.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/1P4A8132.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/1P4A8162.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/1P4A8178.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/1P4A8186.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/1P4A8189.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Da%20Nang/1P4A8047.jpg",
    ],
    phone: "(0236) 7109 299",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Hồ bơi",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "NTC - Nha Trang Center - Tp.Nha Trang",
    name: "NHA TRANG CENTER - TP. NHA TRANG",
    city: "Khánh Hòa",
    ward: "",
    district: "TP. Nha Trang",
    street: "Tầng 4, Tòa nhà Nha Trang Center , 20 Trần Phú, P. Lộc Thọ",
    desc: [
      "Nằm trên đường Trần Phú – tuyến giao thông huyết mạch của thành phố biển Nha Trang, California Fitness Nha Trang mang đến nhiều chương trình đặc biệt đáp ứng được các nhu cầu cụ thể của từng khách hàng cùng hệ thống thiết bị hiện đại từ Hoa Kỳ với vốn đầu tư lên đến 5.000.000 USD.",
      "Không gian hướng biển truyền cảm hứng, chương trình luyện tập tiêu chuẩn quốc tế cùng với các tiện ích thư giãn tích hợp chỉ có tại CLB California Fitness & Yoga Nha Trang chắc chắn sẽ giúp bạn đạt được mục tiêu sức khoẻ và hình thể nhanh chóng. Khám phá ngay!",
      "Toạ lạc tại tầng 4 TTTM Nha Trang Center - vị trí đắc địa với hướng nhìn ra biển xinh đẹp, California Fitness & Yoga Nha Trang chính là không gian luyện tập đưa bạn đến với khoảng trời tự nhiên phong phú với thiết kế cửa sổ lớn bao quanh khu vực máy chạy bộ. Bạn có thể tìm về ốc đảo Yoga bình yên, thả mình trong vũ điệu sôi động tại các lớp Dance/Groupx hay tập luyện chuyên nghiệp cùng HLV cá nhân,...Và phục hồi năng lượng với phòng xông hơi cao cấp thả ga khi trở thành hội viên California Nha Trang hôm nay.",
    ],
    times_days: [
      {
        time: "5:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "5:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5294.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5086.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5422.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5409.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5372.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5353.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A4942.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5225.jpg",
    ],
    phone: "(0258) 7307 899",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "BDS - Bình Dương Square - Tp.Thủ Dầu Một",
    name: "BÌNH DƯƠNG SQUARE - TỈNH BÌNH DƯƠNG",
    city: "Bình Dương",
    ward: "P. Phú Lợi",
    district: "TP. Thủ Dầu Một",
    street: "Bình Dương Square, Tầng 3, Số 1 Phú Lợi",
    desc: [
      "Tọa lạc tại trung tâm thương mại Bình Dương Square, California Fitness & Yoga Center Bình Dương là phòng tập đẳng cấp quốc tế duy nhất tại Bình Dương với diện tích lên đến 16000m2, thỏa mãn nhu cầu luyện tập cho các tín đồ phòng gym tại TP Thủ Dầu Một và khu vực lân cận.",
      "Tập luyện và thư giãn thả ga tại một trong những phòng tập California sang trọng hàng đầu Bình Dương với hơn 100+ lớp học đa dạng hàng tuần cùng với khu vực máy tập chức năng nhập khẩu hoàn toàn từ Ý - Technogym. Khám phá ngay!",
      "Tọa lạc tại vị trí vàng ngay tầng 3 TTTM Bình Dương square, phòng tập California Fitness & Yoga Bình Dương sở hữu diện tích lên đến 16000m2 phân chia thành các khu vực tập luyện chuyên biệt. Với mục tiêu phục vụ tốt nhất cho mọi nhu cầu về thể hình và chăm sóc sức khỏe, chúng tôi tích hợp cả các tiện ích thư giãn và phục hồi năng lượng bên trong khu vực tập luyện: phòng xông hơi cao cấp, quầy thức uống dinh dưỡng, sofa nghỉ dưỡng tại studio Yoga, phòng tắm nóng/lạnh và đặc biệt đây cũng là phòng tập duy nhất có hồ bơi tại Bình Dương.",
    ],
    times_days: [
      {
        time: "5:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4365.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4207.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4228.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4245.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4164.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4259.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4285.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4120.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4058.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Binh%20Duong/California-4105.jpg",
    ],
    phone: "(0274) 7303 999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "NTC - Nha Trang Center - Tp.Nha Trang",
    name: "NHA TRANG CENTER - TP. NHA TRANG",
    city: "Khánh Hòa",
    ward: "",
    district: "TP. Nha Trang",
    street: "Tầng 4, Tòa nhà Nha Trang Center , 20 Trần Phú, P. Lộc Thọ",
    desc: [
      "Là trung tâm thể hình chuẩn quốc tế duy nhất tại TP Biên Hòa, California Fitness and Yoga có không gian tập luyện cực rộng được trang bị thiết bị cao cấp từ Technogym cùng những tiện ích độc quyền như quầy giải khát Califresh, phòng xông hơi ướt và khô phục vụ nhu cầu tập luyện, thư giãn sau mỗi buổi tập.",
      "Không gian hướng biển truyền cảm hứng, chương trình luyện tập tiêu chuẩn quốc tế cùng với các tiện ích thư giãn tích hợp chỉ có tại CLB California Fitness & Yoga Nha Trang chắc chắn sẽ giúp bạn đạt được mục tiêu sức khoẻ và hình thể nhanh chóng. Khám phá ngay!",
      "Toạ lạc tại tầng 4 TTTM Nha Trang Center - vị trí đắc địa với hướng nhìn ra biển xinh đẹp, California Fitness & Yoga Nha Trang chính là không gian luyện tập đưa bạn đến với khoảng trời tự nhiên phong phú với thiết kế cửa sổ lớn bao quanh khu vực máy chạy bộ. Bạn có thể tìm về ốc đảo Yoga bình yên, thả mình trong vũ điệu sôi động tại các lớp Dance/Groupx hay tập luyện chuyên nghiệp cùng HLV cá nhân,...Và phục hồi năng lượng với phòng xông hơi cao cấp thả ga khi trở thành hội viên California Nha Trang hôm nay.",
    ],
    times_days: [
      {
        time: "5:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "5:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5294.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5086.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5422.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5409.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5372.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5353.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A4942.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Nha%20Trang/2B7A5225.jpg",
    ],
    phone: "(0258) 7307 899",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "PBH - Pegasus Plaza - Tp.Biên Hòa",
    name: "PEGASUS PLAZA - BIÊN HÒA",
    city: "Đồng Nai",
    ward: "P. Quyết Thắng",
    district: "TP. Biên Hòa",
    street: "Pegasus Plaza, Tầng 4 & 5, 53-55 Võ Thị Sáu",
    desc: [
      "Tọa lạc tại trung tâm thương mại Bình Dương Square, California Fitness & Yoga Center Bình Dương là phòng tập đẳng cấp quốc tế duy nhất tại Bình Dương với diện tích lên đến 16000m2, thỏa mãn nhu cầu luyện tập cho các tín đồ phòng gym tại TP Thủ Dầu Một và khu vực lân cận.",
      "Vượt chuẩn phòng gym thông thường, California Fitness & Yoga Biên Hoà chính là khu phức hợp tập luyện - thư giãn hiện đại bậc nhất TP Biên Hoà mà bạn không nên bỏ lỡ. Dù mục tiêu của bạn là đốt mỡ, tăng cơ, xả stress hay duy trì sức khoẻ,....California luôn có chương trình tập luyện phù hợp với lịch trình bận rộn của bạn. Khám phá ngay!",
      "Toạ lạc tại tầng 4 & 5 Pegasus Plaza - cao ốc cửa ngõ thành phố Biên Hoa, California Fitness & Yoga quận Biên Hoà với khuôn viên phòng tập thiết kế tinh tế thu hút hàng trăm hội viên đến tập luyện mỗi ngày. Với hệ thống lọc khí khử khuẩn với trang thiết bị được vệ sinh liên tục hàng giờ cùng các tiện ích phục hồi năng lượng tích hợp chắc chắn sẽ mang lại cho bạn trải nghiệm tập luyện an toàn và tiện nghi bậc nhất.",
    ],
    times_days: [
      {
        time: "5:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 21:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4860.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4791.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4762.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4730.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4685.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4481.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4407.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4646.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Bien%20Hoa/California-4620.jpg",
    ],
    phone: "(0251) 730 8999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "VTC - Lapen Center - Tp.Vũng Tàu",
    name: "LAPEN CENTER - VŨNG TÀU",
    city: "Bà Rịa - Vũng Tàu",
    ward: "Phường 9",
    district: "TP. Vũng Tàu",
    street: "Tầng 5, Lapen Center, 33A Đường 30/4",
    desc: [
      "Với trang thiết bị hiện đại nhập khẩu từ Hoa Kỳ, chương trình tập luyện đa dạng chuẩn quốc tế, phòng tập California Fitness and Yoga tại TP Vũng Tàu xứng đáng là địa chỉ luyện tập lý tưởng không chỉ cho du khách mà còn cho những ai tìm kiếm lối sống khỏe mạnh, bền vững.",
      "Được mệnh danh là phòng tập duy nhất sở hữu đầy đủ trang thiết bị nhập khẩu cùng với chương trình rèn luyện đa dạng nhất thành phố biển Vũng Tàu, California Fitness & Yoga chính là tuyên ngôn của phong cách sống năng động đẳng cấp dành cho bạn. Khám phá ngay!",
      "Là một trong 3 CLB được mở vào năm 2019, California Fitness & Yoga Vũng Tàu được kỳ vọng trở thành địa điểm văn hoá, giải trí và rèn luyện sức khoẻ hiện đại bậc nhất tại thành phố biển Vũng Tàu. Với vị trí đắc địa nằm tại tầng 5 & 6 khu TTTM Lapen cùng với thiết kế mở sang trọng, CLB Vũng Tàu tích hợp đầy đủ các dịch vụ dance, yoga, groupX, gym,...sẽ mang lại cho bạn trải nghiệm thượng lưu với chi phí hợp lý.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/VTC_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/Facilities/California-4883.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/Facilities/California-4936.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/Facilities/California-4975.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/Facilities/California-5075.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/Facilities/California-5099.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/Facilities/California-4910.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/Facilities/California-5160.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/Facilities/California-5045.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Vung%20Tau/Facilities/California-5062.jpg",
    ],
    phone: "(0254) 730 0999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "CVC - Vincom Xuân Khánh - Q.Ninh Kiều",
    name: "VINCOM XUÂN KHÁNH - TP. CẦN THƠ",
    city: "Cần Thơ",
    ward: "P. Xuân Khánh",
    district: "Q. Ninh Kiều",
    street: "Vincom Xuân Khánh, Tầng 3, 209 Đường 30/4",
    desc: [
      "California Fitness and Yoga chính là trung tâm thể hình chuẩn quốc tế tiên phong tại Tây Đô với sự đầu tư hơn 5 triệu USD cho những trang thiết bị tân tiến nhất để thỏa mãn nhu cầu luyện tập của giới trẻ Cần Thơ, xứng tầm phòng tập chuẩn 5 sao đầu tiên và duy nhất tại miền Tây.",
      "Thoả sức tập luyện hơn 100+ lớp Dance, Yoga, GroupX, rèn luyện thể lực như các vận động viên chuyên nghiệp tại siêu câu lạc bộ có sức hút nhất tại Cần Thơ ngay hôm nay. California Fitness & Yoga Cần Thơ chính là lựa chọn hoàn hảo cho sức khoẻ của bạn.",
      "Tọa lạc tại tầng 3 Vincom Xuân Khánh - vị trí đắc địa nhất thành phố, California Fitness & Yoga Cần Thơ được đánh giá là không gian tập luyện đẹp nhất khu vực miền Nam Việt Nam. Với thiết kế sang trọng và ấm cúng đậm chất Hoàng Gia: quầy bar có biểu tượng đại bàng quyền lực, hệ thống trang thiết bị nhập khẩu từ Ý, hồ bơi 5 sao trong nhà, võ đài bát giác phục vụ tập võ MMA/Kickfit, studio Yoga yên tĩnh, phòng tập nhóm Dance/GroupX chuẩn mọi khung hình,...Tất cả sẽ mang lại cho bạn trải nghiệm phong cách sống năng động và đẳng cấp.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/CanTho_CVC_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_1.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_2.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_3.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_4.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_5.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_6.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_7.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_8.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_12.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_9.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_10.jpg",
      "https://cali.vn/storage/app/media/2021/Club/Can%20Tho/CVC/Slider/CVC_slider_1900x800px_11.jpg",
    ],
    phone: "(0292) 730 2999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "GDC - Gold View - Q.4",
    name: "GOLDVIEW - QUẬN 4",
    city: "Hồ Chí Minh",
    ward: "Phường 1",
    district: "Quận 4",
    street: "Tầng 3, Goldview, 346 Bến Vân Đồn",
    desc: [
      "Tọa lạc tại tầng 3 trung tâm thương mại Gold View, phòng tập gym California Fitness & Yoga Quận 4 sở hữu các khu vực tập luyện riêng biệt được phân chia khoa học và tích hợp đầy đủ các tiện ích phục hồi năng lượng mở rộng như: phòng xông hơi, phòng tắm, tủ locker, ...đem đến cho khách hàng trải nghiệm tập luyện chuyên nghiệp và tiện nghi nhất.",
      "Là một trong những CLB được xây dựng mới nhất vào năm 2019 theo phong cách tối giản với tông màu xám chủ đạo: không gian rộng rãi, thoáng đãng, thiết bị hiện đại mới 100%. California Fitness & Yoga Quận 4 GoldView cũng là nơi đầu tiên sở hữu khu chức năng chuyên dụng D.A.R.E Devils dành cho hội viên muốn thử thách bản thân.",
      "Tọa lạc tại tầng 3 trung tâm thương mại Gold View, phòng tập gym California Fitness & Yoga Quận 4 sở hữu các khu vực tập luyện riêng biệt được phân chia khoa học và tích hợp đầy đủ các tiện ích phục hồi năng lượng mở rộng như: phòng xông hơi, phòng tắm, tủ locker,...đem đến cho khách hàng trải nghiệm tập luyện chuyên nghiệp và tiện nghi nhất.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GDC/HCM_GDC_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GDC/Facility/TNL-Plaza-Facilties_1.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GDC/Facility/TNL-Plaza-Facilties_2_.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GDC/Facility/TNL-Plaza-Facilties_3.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GDC/Facility/TNL-Plaza-Facilties_4.jpg",
    ],
    phone: "(028) 7308 2277",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "VVO - VIVO City - Q.7",
    name: "VIVO CITY - QUẬN 7",
    city: "Hồ Chí Minh",
    ward: "P. Tân Phong",
    district: "Quận 7",
    street: "SC VivoCity, tầng 4, 1058 Nguyễn Văn Linh",
    desc: [
      "Toạ lạc tại lầu 4 Vivo City, California Fitness & Yoga Quận 7 được mệnh danh là phòng tập được hội viên yêu thích nhất trong các phòng tập California. Từng chi tiết trong không gian này được thiết kế và hoàn thiện theo tiêu chuẩn phòng tập Quốc tế khi tích hợp các dịch vụ thư giãn chuyên sâu như phòng xông hơi sauna, Yoga studio cao cấp... tạo nên trải nghiệm tập luyện cao cấp chưa từng có tại Việt Nam.",
      "California Fitness & Yoga quận 7 - sự lựa chọn hàng đầu dành cho các khách hàng có nhu cầu tận hưởng, trải nghiệm dịch vụ tập luyện 5 Sao hàng đầu Việt Nam. Hệ thống máy tập đa dạng, chương trình tập luyện chuyên sâu và không gian tích hợp đa dạng tiện ích như phòng xông hơi, Yoga studio cao cấp... sẽ giúp hội viên có thêm cảm hứng cho mỗi giờ phút luyện tập. Khám phá ngay!",
      "Toạ lạc tại lầu 4 Vivo City, California Fitness & Yoga quận 7 được mệnh danh là phòng tập được hội viên yêu thích nhất trong các phòng tập California. Từng chi tiết trong không gian này được thiết kế và hoàn thiện theo tiêu chuẩn phòng tập Quốc tế khi tích hợp các dịch vụ thư giãn chuyên sâu như phòng xông hơi sauna, bể sục Jacuzzi, hồ bơi cao cấp,...tạo nên trải nghiệm tập luyện cao cấp chưa từng có tại Việt Nam.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VVO/HCM_VVO_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VVO/VVO-Centarea.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VVO/VVO-Centchangeroom.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VVO/VVO-CFYarea.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VVO/VVO-Gxroom.jpg",
    ],
    phone: "(028) 7107 7899",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "TDU - Thảo Điền Pearl - Q.2",
    name: "THẢO ĐIỀN PEARL - QUẬN 2",
    city: "Hồ Chí Minh",
    ward: "P. Thảo Điền",
    district: "Quận 2",
    street: "Tầng 3, Thảo Điền Pearl, 12 Quốc Hương",
    desc: [
      "Điểm khác biệt của California Fitness & Yoga Thảo Điền quận 2 so với các trung tâm thể hình thông thường chính là các lớp học võ thuật tổng hợp nhóm đẳng cấp Quốc Tế, đem lại cho bạn vóc dáng hoàn hảo và tinh thần tuyệt vời.",
      "Điểm khác biệt của California Fitness & Yoga Thảo Điền quận 2 so với các trung tâm thể hình thông thường chính là các lớp học võ thuật tổng hợp nhóm đẳng cấp Quốc Tế, đem lại cho bạn vóc dáng hoàn hảo và tinh thần tuyệt vời.",
      "Toạ lạc tại tầng 3 trong cùng khuôn viên Yoga Plus, toàn bộ cơ sở vật chất của California Fitness & Yoga Thảo Điền quận 2 đều mang đẳng cấp 5 sao với môi trường tập luyện chuyên nghiệp. Các HLV đều là các võ sư giàu kinh nghiệm và đạt danh tiếng lớn trên đấu trường quốc tế. Ngoài ra, California quận 2 còn có Moving Theater - phòng đạp xe tích hợp xem phim, hồ Jacuzzi thư giãn,..sẽ đem đến cho bạn trải nghiệm luyện tập hoàn toàn khác biệt.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/TDU_Thumbnail.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/Facilities/TDU_Facilities_1.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/Facilities/TDU_Facilities_2.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/Facilities/TDU_Facilities_3.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/Facilities/TDU_Facilities_4.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/Facilities/TDU_Facilities_5.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/Facilities/TDU_Facilities_6.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/Facilities/TDU_Facilities_7.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/Facilities/TDU_Facilities_8.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDU/Facilities/TDU_Facilities_9.jpg",
    ],
    phone: "(028) 7302 1999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "TDC - Thủ Đức Club - Q.Thủ Đức",
    name: "VINCOM - TP. THỦ ĐỨC",
    city: "Hồ Chí Minh",
    ward: "P. Bình Thọ",
    district: "TP. Thủ Đức",
    street: "Tầng 3, Vincom Thủ Đức, 216 Võ Văn Ngân",
    desc: [
      "Tọa lạc tại tầng 3 khu TTTM Vincom Thủ Đức, California Fitness & Yoga Võ Văn Ngân với thiết kế dàn trải trong cùng một tầng rộng thoáng, hệ thống máy tập Technogym đầy đủ cùng với chương trình tập luyện đa dạng chắc chắn là lựa chọn lý tưởng dành cho lịch trình bận rộn của bạn. Sau mỗi giờ luyện tập, bạn có thể tận hưởng không giới hạn các tiện ích phục hồi năng lượng như phòng xông hơi ướt/khô, phòng tắm nóng/lạnh, quầy thức uống dinh dưỡng Califresh,...được tích hợp ngay trong khuôn viên Câu lạc bộ.",
      "California Fitness & Yoga Võ Văn Ngân - môi trường tập luyện luôn bắt kịp các xu hướng mới nhất từ thế giới. Với chương trình luyện tập đa dạng cùng với hệ thống trang thiết bị đầy đủ nhập khẩu từ Technogym (Ý) chắc chắn chính là tuyên ngôn phong cách sống đẳng cấp dành cho bạn. Khám phá ngay!",
      "Tọa lạc tại tầng 3 khu TTTM Vincom Thủ Đức, California Fitness & Yoga Võ Văn Ngân với thiết kế dàn trải trong cùng một tầng rộng thoáng, hệ thống máy tập Technogym đầy đủ cùng với chương trình tập luyện đa dạng chắc chắn là lựa chọn lý tưởng dành cho lịch trình bận rộn của bạn. Sau mỗi giờ luyện tập, bạn có thể tận hưởng không giới hạn các tiện ích phục hồi năng lượng như phòng xông hơi ướt/khô, phòng tắm nóng/lạnh, quầy thức uống dinh dưỡng Califresh,...được tích hợp ngay trong khuôn viên Câu lạc bộ.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7907.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7799.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7762.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7727.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7714.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7699.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7639.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7679.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7602.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDC/1P4A7884.jpg",
    ],
    phone: "(028) 7109 6899",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "PCO - PICO Plaza - Q.Tân Bình",
    name: "PICO PLAZA - QUẬN TÂN BÌNH",
    city: "Hồ Chí Minh",
    ward: "Phường 12",
    district: "Q. Tân Bình",
    street: "Tầng 3, Vincom Thủ Đức, 216 Võ Văn Ngân",
    desc: [
      "Trung tâm California Fitness and Yoga tại Tân Bình sở hữu khuôn viên rộng rãi và thiết bị hiện đại cùng chương trình tập luyện vô cùng đa dạng bao gồm lớp Group X, Yoga, Dance, Crossfit, MMA và Kickfit trải đều trong tuần.",
      "Được mệnh danh là một trong các CLB có quy mô hoành tráng nhất từ trước đến nay trên toàn hệ thống, California Fitness & Yoga Pico quận Tân Bình với khuôn viên rộng rãi sở hữu đầy đủ các trang thiết bị cho các môn như MMA, Kickfit, đường chạy trong nhà. Khám phá ngay!",
      "Được thành lập vào năm 2013, phòng tập California Fitness & Yoga quận Tân Bình toạ lạc tại tầng 3 TTTM Pico Plaza hứa hẹn sẽ là nơi bạn dễ dàng tìm thấy nguồn cảm hứng và năng lượng tập luyện. Khám phá các lớp thể dục nhóm đa dạng, phương pháp rèn luyện hàng đầu từ các HLV chuyên nghiệp, không gian tập luyện thoáng đãng và tiện lợi tích hợp các tiện ích hồi phục năng lượng như phòng xông hơi, phòng tắm có tủ cất giữ tư trang rộng lớn, sofa thư giãn trước các lớp học Yoga.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2156.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2036.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2214.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2124.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2126.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2116.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2111.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2019.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2011.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A1977.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PCO/1P4A2093.jpg",
    ],
    phone: "(028) 7109 1899",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "CTC - CALI Tower - Q.Phú Nhuận",
    name: "CALI TOWER - QUẬN PHÚ NHUẬN",
    city: "Hồ Chí Minh",
    ward: "Phường 2",
    district: "Q. Phú Nhuận",
    street: "Tòa nhà Cali Tower, 464-466-468 Phan Xích Long",
    desc: [
      "Phòng tập California Fitness and Yoga Phú Nhuận được mệnh danh là cơ sở “đậm chất California” nhất vì tọa lạc tại Tòa nhà riêng của California Fitness and Yoga và đặc biệt cơ sở còn sở hữu hồ bơi rooftop trên tầng cao nhất của tòa nhà.",
      "Một cơ sở vô cùng đậm chất Cali toạ lạc ở vị trí đắc địa ngay ngã tư Phan Xích Long rất thuận tiện cho quý hội viên trong những ngày lịch trình bận rộn. California Fitness Phú Nhuận được mệnh danh là địa điểm có lịch học các bộ môn lí tưởng được đông đảo hội viên yêu thích. Khám phá ngay hôm nay!",
      "California Tower Club là siêu Câu lạc bộ thứ 26 - một trong những phòng tập nổi bật tọa lạc tại quận Phú Nhuận - khu vực trọng điểm của thành phố. Cali Tower là tòa tháp đầu tiên thuộc 100% quyền sở hữu của California Fitness and Yoga với 8 lầu chức năng như phòng tập Yoga, phòng máy tập Cardio như máy chạy bộ, chạy xe đạp,..., phòng tập các bộ môn theo nhóm Group X, Dance studio, khu vực Centuryon sang chảnh. Đây cũng là nơi sở hữu hồ bơi nước nóng trong nhà ở tầng 7 dành riêng cho các hội viên Centuryon.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/CTC/2B7A0594.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/CTC/2B7A0507.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/CTC/2B7A0549.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/CTC/2B7A0546.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/CTC/2B7A0565.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/CTC/2B7A0535.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/CTC/2B7A0470.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/CTC/2B7A0445.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/CTC/2B7A0430.jpg",
    ],
    phone: "(028) 7100 7999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "HVP - Hùng Vương Plaza - Q.5",
    name: "HÙNG VƯƠNG PLAZA - QUẬN 5",
    city: "Hồ Chí Minh",
    ward: "Phường 12",
    district: "Quận 5",
    street: "Tầng 5 Hùng Vương Plaza, 126 Hùng Vương",
    desc: [
      "Được xem là viên gạch nền móng trong chuỗi hệ thống phòng tập cao cấp tại Việt Nam, trung tâm California Fitness and Yoga Quận 5 hội tụ đủ các yếu tố của một phòng tập chuẩn quốc tế: mô hình tập luyện đa dạng, phương pháp thể hình cập nhật liên tục và các dịch vụ hồi phục năng lượng tốt nhất",
      "Là nơi đặt nền móng đầu tiên cho sự ra đời của California Fitness & Yoga, phòng tập California quận 5 thu hút hàng trăm lượt khách đến luyện tập mỗi ngày. Với dịch vụ phòng gym mang đẳng cấp 5* và chương trình tập luyện chuẩn quốc tế đa dạng, California quận 5 sẽ mang đến cho bạn những trải nghiệm khác biệt so với những phòng tập thông thường.",
      "Toạ lạc tại tầng 5 Hùng Vương Plaza thuộc khu Chợ Lớn sầm uất, California Fitness & Yoga quận 5 với không gian rộng lớn, thoáng mát cùng chương trình hội viên đa dạng sẽ giúp bạn dễ dàng đạt các mục tiêu sức khoẻ như tăng cân, giảm cân, duy trì vóc dáng với chương trình tập luyện phù hợp.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A6579.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A6555.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A6709.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A6712.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A6754.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A7242.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A7270.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A6771.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A6803.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/HVP/1P4A6816.jpg",
    ],
    phone: "(028) 7109 5999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "SCC - CenturyOn Saigon Centre - Q.1",
    name: "SAIGON CENTER - QUẬN 1",
    city: "Hồ Chí Minh",
    ward: "P. Bến Nghé",
    district: "Quận 1",
    street: "Lầu 6 - Saigon Center, 65 Lê Lợi",
    desc: [
      "Có vị trí vàng tại 3 tầng 6-7-8 trung tâm Saigon Center với thiết kế theo quý tộc, phòng tập California Centuryon Saigon Center kết hợp cùng trung tâm Hypoxi và Thẩm mỹ viện Eri trong bán kính 1km, tạo nên một hệ sinh thái cao cấp giúp hội viên nhanh chóng đạt được thể hình hoàn mỹ.",
      "Được bình chọn là 1 trong 4 phòng tập gym sang trọng ở Châu Á, California Centuryon SaiGon Centre (SCC) tại quận 1 sẽ mang đến cho bạn những giá trị đỉnh cao trong việc rèn luyện sức khoẻ. Trải nghiệm miễn phí không gian tập luyện hoàn hảo và đẳng cấp thượng lưu ngay hôm nay!",
      "Toạ lạc tại tầng 6,7,8 Trung tâm Thương mại Saigon Centre, California Centuryon có tổng diện tích 2.200m2 được thiết kế với 2 gam màu: đen và vàng ánh kim đặc trưng tạo nên phong cách Hoàng Tộc sang trọng, đẳng cấp xứng tầm với vị trí đắc địa.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Chủ Nhật",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/HCM_900x600.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_10.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_03.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_01.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_02.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_04.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_05.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_06.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_07.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_08.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/SCC/Facility%20Slider/SCC_Slider_1900x800px_09.jpg",
    ],
    phone: "(028) 7106 5999",
    title_small: "TIỆN NGHI",
    infor: [
      "Studio Yoga",
      "Studio Dance/GroupX",
      "Studio đạp xe thực tế ảo",
      "Máy tập nhập khẩu",
      "Phòng xông hơi ướt/khô",
      "Hồ thuỷ lực",
      "Hồ bơi riêng tư",
      "Quầy bar Califresh",
      "Tủ khoá rộng lớn",
      "Bàn trang điểm",
      "Máy sấy tóc",
    ],
  },
  {
    title: "VMC - Viet Market - Q.6",
    name: "VIET MARKET - QUẬN 6",
    city: "Hồ Chí Minh",
    ward: "Phường 8",
    district: "Quận 6",
    street: "Tầng 3 Viet Market, 634Bis Phạm Văn Chí",
    desc: [
      "Trung tâm California Fitness and Yoga Quận 6 là một trong những trung tâm mới nhất trong chuỗi 35 câu lạc bộ toạ lạc tại khu vực đắc địa. Với trang thiết bị tân tiến nhất cùng những chương trình tập luyện cập nhật mới nhất, CLB quận 6 trở thành không gian tập luyện được nhiều hội viên ở khu vực phía Tây thành phố yêu thích.",
      "Là câu lạc bộ mới nhất trong chuỗi hệ thống phòng tập California Fitness & Yoga, phòng tập California quận 6 sở hữu trang thiết bị hiện đại bậc nhất. Môi trường tập luyện hứa hẹn sẽ mang lại thử thách thay đổi hình thể thú vị và hấp dẫn dành cho bạn khi đăng ký tập thử miễn phí hôm nay.",
      "Toạ lạc tại tầng 3 Việt Market - vị trí thuận lợi ngay trung tâm quận 6 với 2 mặt tiền Phạm Văn Chí và Văn Thân. Đây là một trong các CLB California được đầu tư quy mô lớn về trang thiết bị, không gian sang trọng cùng với chương trình tập luyên Quốc tế đa dạng từ gym, yoga, dance, lớp tập nhóm GroupX,...sẽ giúp hội viên nhanh chóng đạt được mục tiêu hình thể mong muốn.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VMC/California-3004.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VMC/California-2980.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VMC/California-2842.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VMC/California-2634.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VMC/California-2552.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VMC/California-2531.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VMC/California-2508.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VMC/California-2885.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/VMC/California-2493.jpg",
    ],
    phone: "(028) 7301 9922",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "AMU - AEON MALL - Q.Tân Phú",
    name: "AEON MALL - QUẬN TÂN PHÚ",
    city: "Hồ Chí Minh",
    ward: "P. Sơn Kỳ",
    district: "Q. Tân Phú",
    street: "Aeon Mall Tân Phú, 30 Bờ Bao Tân Thắng",
    desc: [
      "Trung tâm California Fitness and Yoga tại AEON Mall Tân Phú sở hữu phương pháp độc đáo với những bài tập hạng nặng và chương trình tập được thiết kế khác biệt cho hội viên chuyên nghiệp như: những lớp kickboxing, lớp võ thuật và những bài tập giãn cơ giúp phục hồi nhanh chóng sau buổi tập nặng.",
      "Toạ lạc tại trung tâm mua sắm trọng điểm Aeon Mall Tân Phú với cơ sở vật chất tiêu chuẩn Quốc tế cùng với thiết kế khác biệt theo tiêu chuẩn các vận động viên UFC, chi nhánh California tại Tân Phú hứa hẹn sẽ trở thành địa điểm lý tưởng cho việc rèn luyện sức khoẻ và hình thể mơ ước dành cho bạn.",
      "Câu lạc bộ California Fitness & Yoga quận Tân Phú là CLB thứ 2 xây dựng theo mô hình võ thuật kết hợp với võ thuật. Toạ lạc tại tầng 1 Aeon Mall Tân Phú, trung tâm California được sở hữu hệ thống trang thiết bị đẳng cấp như Octagon hình bát giác, sàn boxing chất lượng cao và đội ngũ HLV đạt nhiều thành tích trên đấu trường Quốc Tế. Bên cạnh đó, CLB còn tích hợp các dịch vụ đạp xe xem phim, bể sục Jacuzzi, phòng xông hơi,...đem đến cho bạn những trải nghiệm tập luyện độc đáo.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMU/California-3907.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMU/California-3892.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMU/California-3632.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMU/California-3679.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMU/California-3694.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMU/California-3713.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMU/California-3838.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMU/California-3762.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMU/California-3762.jpg",
    ],
    phone: "(028) 7303 9922",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "FDC - Parkson Flemington - Q.11",
    name: "PARKSON FLEMINGTON - QUẬN 11",
    city: "Hồ Chí Minh",
    ward: "Phường 15",
    district: "Quận 11",
    street: "Tầng 5 Parkson Flemington, 184 Lê Đại Hành",
    desc: [
      "Là một trong những cơ sở đầu tiên tại TPHCM, California Fitness and Yoga tại tòa nhà Parkson Flemington có thiết kế không gian tập luyện tối ưu về diện tích, tạo ra sự thoáng đãng khác biệt. Không chỉ sở hữu thiết bị luyện tập hiện đại mà CLB California quận 11 còn cung cấp những tiện ích chăm sóc sức khỏe, xông hơi",
      "Vượt qua mọi giới hạn của bạn tại California Diamond quận 11. Toạ lại tại vị trí thuận lợi - khu trung tâm thương mại Flemington Parkson, với màu sắc chủ đạo đen tuyền kết hợp với màu bạc mang lại sự thanh lịch và một không gian xứng tầm cho bạn trải nghiệm luyện tập và hồi phục đẳng cấp 5 sao. Khám phá ngay hôm nay!",
      "Toạ lạc tại lầu 5 toà nhà Flemington quận 11, CLB California Diamond quận 11 được mệnh danh là một trong những địa điểm tập luyện cao cấp và sang trọng nhất trong chuỗi hệ thống phòng tập California. Với thiết kế đặc biệt và được đầu tư trang thiết bị hiện đại nhập khẩu hoàn toàn từ Technogym cùng với các tiện ích chăm sóc và hồi phục sức khoẻ, California quận 11 chính là lựa chọn an toàn cho sức khoẻ và cuộc sống của bạn.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/FDC/2B7A4336.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/FDC/2B7A4382.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/FDC/2B7A4411.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/FDC/2B7A4444.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/FDC/2B7A4489.jpg",
    ],
    phone: "(028) 7109 7889",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "PPC - Pearl Plaza - Q.Bình Thạnh",
    name: "PEARL PLAZA - QUẬN BÌNH THẠNH",
    city: "Hồ Chí Minh",
    ward: "Phường 25",
    district: "Q. Bình Thạnh",
    street: "Pearl Plaza, Tầng 3, 561A Điện Biên Phủ",
    desc: [
      "Trung tâm California Fitness and Yoga quận Bình Thạnh là phòng tập chuyên sâu về thể hình với tập hợp những huấn luyện viên chuyên môn cao trong ngành và những lớp học “nặng ký” giúp bạn nhanh chóng sở hữu một thân hình hoàn mỹ bằng phương pháp tập luyện khoa học.",
      "Hiện đại, sang trọng và là nơi được đa số người nổi tiếng yêu thích, phòng tập California Fitness & Yoga quận Bình Thạnh chính là sự lựa chọn hoàn hảo xứng tầm với phong cách sống của bạn. Với các tiện ích tích hợp như phòng xông hơi, quầy thức uống dinh dưỡng Califresh cùng với thương hiệu thẩm mỹ Eri Clinic xung quanh, tất cả sẽ mang lại cho bạn trải nghiệm chăm sóc sức khỏe độc đáo. Khám phá ngay!",
      "Đặt tại tầng 3 trung tâm thương mại Pearl Plaza với không gian rộng hơn 2000m2, các khu vực tập luyện tại California Fitness quận Bình Thạnh được bố trí tối ưu hoá diện tích. Với hệ thống máy tập hiện đại và đầy đủ nhập khẩu hoàn toàn từ Technogym luôn được vệ sinh, kiểm tra hằng ngày cùng với các tiện ích phục hồi năng lượng cao cấp mang đến không gian tập luyện đảm bảo an toàn cho quý Hội viên. Bên cạnh đó đặt cạnh CLB quận Bình Thạnh là viện thẩm mỹ Nhật Bản Eri Clinic hứa hẹn sẽ mang đến cho bạn trải nghiệm chăm sóc sức khoẻ làm đẹp toàn diện.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PPC/2B7A5878p.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PPC/2B7A5919.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PPC/2B7A5938.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PPC/2B7A5977.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PPC/2B7A6016.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PPC/2B7A6027.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PPC/2B7A6058.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PPC/2B7A6093.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/PPC/2B7A6102.jpg",
    ],
    phone: "(028) 7109 7899",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "LMC - CenturyOn Landmark 81 - Q.Bình Thạnh",
    name: "LANDMARK 81 - QUẬN BÌNH THẠNH",
    city: "Hồ Chí Minh",
    ward: "Phường 22",
    district: "Q. Bình Thạnh",
    street: "Lầu 3 The Landmark 81, 772 Điện Biên Phủ",
    desc: [
      "Nằm tại tầng 3 ở Landmark 81, California Centuryon Landmark được chính tay các kiến trúc sư Germany thiết kế để trở thành một phòng tập 5 sao chuẩn quốc tế đáp ứng nhu cầu tập luyện của giới thượng lưu Sài Thành với tổng diện tích đến 2.250m2. Đặc biệt đây là CLB đầu tiên tại Việt Nam có bộ môn Yoga nước.",
      "Trải nghiệm nhiều cái nhất chỉ có tại California Centuryon Landmark 81 - một trong những địa điểm tập luyện thu hút giới thượng lưu, doanh nhân thành đạt và các nghệ sĩ nổi tiếng. Cùng khám phá ngay hôm nay!",
      "Với tổng diện tích lên đến 2250m2, California Landmark 81 được thiết kế bởi các kiến trúc sư từ Đức dưới sự giám sát của ông Micheal Wong - giám đốc thiết kế của California Fitness & Yoga để đảm bảo sự tinh tế và đẳng cấp đến từng centimet. Điểm nhấn của CLB này là việc sử dụng các tấm kính đặc biệt để đón toàn bộ ánh sáng tự nhiên mang đến cảm giác trong lành và thoải mái đến cho quý hội viên. Ngoài ra, đây cũng là CLB đầu tiên tại Việt Nam mang bộ môn Yoga nước được giảng dạy bởi các Yogi Ấn Độ chuyên nghiệp cùng với hồ tập chuẩn chỉnh chắc chắn sẽ khiến cả những vị khách hàng khó tính nhất hài lòng.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Chủ Nhật",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3593.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3545.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3425.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3417.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3369.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3360.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3299.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3150.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3133.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LMC/California-3107.jpg",
    ],
    phone: "(028) 7309 2999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "LTC - LIM Tower - Q.3",
    name: "LIM TOWER - QUẬN 3",
    city: "Hồ Chí Minh",
    ward: "Phường 6",
    district: "Quận 3",
    street: "Tầng 2 Toà nhà Lim Tower II, Số 62 A đường Cách Mạng Tháng Tám",
    desc: [
      "Là một trong những phòng tập cao cấp đầu tiên tại Việt Nam, California Fitness and Yoga Quận 3 sở hữu trang thiết bị hiện đại bậc nhất, các khu vực tập luyện riêng biệt được thiết kế cực kì tinh tế đáp ứng những nhu cầu khác nhau của hội viên.",
      "Sở hữu vị trí thuận lợi ngay tại trung tâm thành phố, California Fitness & Yoga quận 3 hứa hẹn sẽ là nơi giúp bạn dễ dàng duy trì lối sống khoẻ mạnh cho lịch trình bận rộn của mình.",
      "Nằm ngay ngã tư Võ Văn Tần và CMT8 trong toà nhà Lim Tower 2, California Fitness & Yoga quận 3 sở hữu không gian tập luyện rộng lớn phân thành 4 tầng. Cơ sở trang bị đầy đủ hệ thống máy tập nhập khẩu từ Technogym được bố trí hướng nhìn ra cửa sổ, chương trình tập luyện đa dạng với lịch học liên tục. Trung tâm California quận 3 chính là lựa chọn an toàn cho sức khoẻ của bạn.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A3041.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A0690.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A0725.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A0673.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A0622.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A0765.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A0796.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A0614.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A0651.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/LTC/2B7A0552.jpg",
    ],
    phone: "(028) 7109 6889",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "GMC - GIGA MALL - Q.Thủ Đức",
    name: "GIGA MALL - TP. THỦ ĐỨC",
    city: "Hồ Chí Minh",
    ward: "Hiệp Bình Chánh",
    district: "TP. Thủ Đức",
    street: "Tầng 4 TTTM Gigamall, 242 Phạm Văn Đồng",
    desc: [
      "Một lựa chọn khác cho những hội viên tại TP Thủ Đức là phòng tập tại Giga Mall Thủ Đức, phòng tập sử dụng công nghệ và phương pháp thể hình hàng đầu Đông Nam Á với trang thiết bị tập luyện nhập khẩu 100% từ Hoa Kỳ Technogym.",
      "Là CLB thứ 32 trong chuỗi hệ thống phòng tập cao cấp, California Fitness & Yoga GigaMall quận Thủ Đức chính là CLB đầu tiên được thực hiện đầu tư nâng cấp và cải tiến theo phong cách mới nhất. Bạn sẽ được trải nghiệm tất cả các chương trình luyện tập từ dance, yoga, group X, đạp xe, gym,....có chất lượng hàng đầu tại Việt Nam. Khám phá ngay!",
      "Toạ lạc tới tầng 4 khu TTTM Gigamall với tổng diện tích 2700m2, California Gigamall Thủ Đức đặc biệt thiết kế riêng 650m2 dành cho khu vực hội viên cao cấp California Centuryon, có tích hợp hồ bơi trong nhà bên trong khu vực VIP. Đây cũng là nơi được đầu tư đầy đủ các loại máy móc đáp ứng cho việc tập luyện mọi nhóm cơ trên cơ thể. Không gian rộng thoáng, sang trọng hứa hẹn sẽ mang lại những trải nghiệm ấn tượng và khó quên dành cho bạn.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2442.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2247.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2178.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2225.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2163.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2330.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2200.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2267.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2397.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GMC/California-2341.jpg",
    ],
    phone: "(028) 7306 4888",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Hồ bơi",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "GVC - SAIGON MALL - Q.Gò Vấp",
    name: "SÀI GÒN MALL - QUẬN GÒ VẤP",
    city: "Hồ Chí Minh",
    ward: "Phường 10",
    district: "Q. Gò Vấp",
    street: "Tầng 3 Sài Gòn Mall, 2A Phan Văn Trị",
    desc: [
      "Là câu lạc bộ mới trong chuỗi 35 câu lạc bộ cao cấp, phòng tập California Fitness and Yoga tại quận Gò Vấp sẽ làm hài lòng các hội viên với thiết kế đương đại sang trọng cùng cơ sở hạ tầng cao cấp bên cạnh những chương trình tập luyện được cập nhật liên tục.",
      "Ngắm nhìn cuộc sống bận rộn từ tầng 3 Saigon Mall, mọi không gian tại California Fitness & Yoga quận Gò Vấp được thiết kế để truyền cảm hứng. Tất cả các khu vực, thiết bị nhập khẩu hoàn toàn từ Technogym được đầu tư để mang đến năng lượng bùng nổ dành cho bạn. Khám phá ngay hôm nay!",
      "Tọa lạc tại vị trí đẹp ngay góc ngã tư Phan Văn Trị và Nguyễn Oanh, California Fitness & Yoga quận Gò Vấp được mệnh danh là địa điểm yêu thích đặc biệt của các tín đồ Yoga bởi phòng tập sở hữu nhiều studio Yoga trong đó có Hot Studio Yoga rất thích hợp dành cho các hội viên có nhu cầu tập Yoga giảm cân. Bên cạnh đó, California quận Gò Vấp còn sở hữu chương trình tập luyện đa dạng khác như Dance, tập nhóm GroupX, Gym, MMA,....",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/GVC/HCM_GVC_900x600.jpg",
      "https://cali.vn/storage/app/media/old/club/qu%E1%BA%ADn%204/Facilties_1.png",
      "https://cali.vn/storage/app/media/old/club/qu%E1%BA%ADn%204/TNL-Plaza-Facilties_2.png",
      "https://cali.vn/storage/app/media/old/club/qu%E1%BA%ADn%204/TNL-Plaza-Facilties_3.jpg",
    ],
    phone: "(028) 7309 7999",
    title_small: "TIỆN NGHI",
    infor: [
      "Khu vực gym",
      "Yoga studio",
      "Group X studio",
      "Cycling studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực thư giãn",
      "Lồng MMA",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
    ],
  },
  {
    title: "AMY - AEON MALL - Q.Bình Tân",
    name: "AEON MALL - QUẬN BÌNH TÂN",
    city: "Hồ Chí Minh",
    ward: "P. Bình Trị Đông",
    district: "Q. Bình Tân",
    street: "Tầng 2 Aeon Mall, Đường 17A",
    desc: [
      "Đến với Trung tâm California Fitness & Yoga AEON Mall Bình Tân, bạn sẽ có cơ hội trải nghiệm những loại hình Yoga nâng cao như Yoga trên không, Yoga với bóng hay đặc biệt là Yoga trên mặt phẳng nghiêng với sự hướng dẫn tận tâm từ các chuyên gia Yogi Ấn Độ. Đặc biệt, mỗi lớp học đều được bố trí một trợ giảng phiên dịch, giúp hỗ trợ người tập bắt nhịp với lớp học một cách dễ dàng và đạt hiệu quả tối đa.",
      "Một không gian Yoga xanh, tĩnh lặng, dễ chịu tuyệt đối ngay giữa lòng thành phố nhộn nhịp. Đó là những trải nghiệm tuyệt vời dành cho bạn sau một ngày làm việc bận rộn. Khám phá ngay California Fitness & Yoga quận Bình Tân ngay hôm nay!",
      "Tọa lạc tại vị trí đắc địa tầng 2 khu TTTM Aeon Bình Tân, California Fitness & Yoga Bình Tân được ví như thiên đường dành cho các tín đồ Yoga thực thụ. Bước vào phòng tập, bạn sẽ cảm thấy bình yên với mùi thảo mộc nhẹ nhàng lan toả cùng với điệu nhạc du dương thiền định. California Bình Tân chính là không gian yoga hiếm hoi tại Việt Nam đem lại cho bạn trải nghiệm yoga hoàn toàn khác biệt.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2023/Club/AMY/AMY-Thumbnail_900x600px.png",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMY/Facility%20Slider/AMY_slide_1900x800px_05.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMY/Facility%20Slider/AMY_slide_1900x800px_04.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMY/Facility%20Slider/AMY_slide_1900x800px_03.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMY/Facility%20Slider/AMY_slide_1900x800px_02.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMY/Facility%20Slider/AMY_slide_1900x800px_07.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/AMY/Facility%20Slider/AMY_slide_1900x800px.jpg",
    ],
    phone: "(028) 7107 8989",
    title_small: "TIỆN NGHI",
    infor: [
      "Yoga studio",
      "Quầy Califresh",
      "Sauna xông hơi",
      "Khu vực Centuryon",
      "Phòng trang điểm",
      "Phòng thay đồ",
      "Yoga Intrinity",
    ],
  },
  {
    title: "TDY - Yoga Plus Thảo Điền Pearl - Q.2",
    name: "YOGA PLUS - THẢO ĐIỀN QUẬN 2",
    city: "Hồ Chí Minh",
    ward: "P. Thảo Điền",
    district: "Quận 2",
    street: "Số 12 Quốc Hương",
    desc: [
      "Như một viên ngọc trai ẩn mình trong tòa nhà Thảo Điền Pearl, phòng tập Yoga Plus Quận 2 chính là một không gian luyện tập lý tưởng cho các tín đồ Yoga với các lớp Yoga có 1-0-2 tại Việt Nam: Yoga với thảm nghiêng (Intrinity); Yoga trên không;...",
      "Trải nghiệm miễn phí thiên đường Yoga đỉnh cao dành cho các tín đồ Yoga ngay hôm nay. Bạn sẽ được trải nghiệm các loại hình Yoga mới chưa từng có tại Việt Nam và bộ môn Intrinity độc quyền tại California.",
      "Toạ lạc tại tầng 3 Thảo Điền Pearl Quốc Hương gần khu dân cư cao cấp với không gian Yoga ấm cúng, chương trình Yoga đa dạng và độc nhất Đông Nam Á, Yoga Plus Thảo Điền quận 2 chính là thiên đường Yoga đích thực dành cho các hội viên yêu thích trải nghiệm Yoga chuyên sâu.",
    ],
    times_days: [
      {
        time: "6:00 - 22:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDY/CLUB-PHOTOS_TDY_HIRES_2016_0874.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDY/CLUB-PHOTOS_TDY_HIRES_2016_0893.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDY/CLUB-PHOTOS_TDY_HIRES_2016_0951.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDY/CLUB-PHOTOS_TDY_HIRES_2016_0963.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDY/CLUB-PHOTOS_TDY_HIRES_2016_0972.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDY/CLUB-PHOTOS_TDY_HIRES_2016_0947.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDY/CLUB-PHOTOS_TDY_HIRES_2016_0933.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDY/CLUB-PHOTOS_TDY_HIRES_2016_0943.jpg",
      "https://cali.vn/storage/app/media/2021/Club/HO%20CHI%20MINH/TDY/CLUB-PHOTOS_TDY_HIRES_2016_0929.jpg",
    ],
    phone: "(028) 7303 1999",
    title_small: "TIỆN NGHI",
    infor: [
      "Studio Yoga",
      "Khu vực tập chức năng",
      "Dụng cụ hỗ trợ",
      "Máy tập nhập khẩu",
      "Phòng xông hơi ướt/khô",
      "Gian hàng thời trang",
      "Quầy bar Lounge ép lạnh",
      "Tủ khoá rộng lớn",
      "Bàn trang điểm",
      "Máy sấy tóc",
    ],
  },
  {
    title: "JCQ - California Active Cống Quỳnh - Q.1",
    name: "CALIFORNIA ACTIVE - CỐNG QUỲNH, QUẬN 1",
    city: "Hồ Chí Minh",
    ward: "Phường Nguyễn Cư Trinh",
    district: "Quận 1",
    street: "A36B Cống Quỳnh",
    desc: [
      "Trẻ trung, dễ tiếp cận và tập theo cách bạn muốn. California Active hướng đến trải nghiệm tập luyện dành cho tất cả mọi người muốn một phòng gym tiêu chuẩn quốc tế ngay nơi mình sống và dễ dàng đến luyện tập nhanh hơn bao giờ hết.",
      "Trẻ trung, dễ tiếp cận và tập theo cách bạn muốn. California Active hướng đến trải nghiệm tập luyện dành cho tất cả mọi người muốn một phòng gym tiêu chuẩn quốc tế ngay nơi mình sống và dễ dàng đến luyện tập nhanh hơn bao giờ hết.",
      "Toạ lạc tại A36B Cống Quỳnh gần khu dân cư cao cấp với không gian Yoga ấm cúng, chương trình Yoga đa dạng và độc nhất Đông Nam Á, Yoga Plus Thảo Điền quận 2 chính là thiên đường Yoga đích thực dành cho các hội viên yêu thích trải nghiệm Yoga chuyên sâu.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2022/Club/JCQ/JCQ-thumbnail.jpg",
      "https://cali.vn/storage/app/media/2022/Club/JCQ/JCQ-facility-1900x800_Functional.jpg",
      "https://cali.vn/storage/app/media/2022/Club/JCQ/JCQ-facility-1900x800_studio.jpg",
      "https://cali.vn/storage/app/media/2022/Club/JCQ/JCQ-facility-1900x800_treadmill.jpg",
      "https://cali.vn/storage/app/media/2022/Club/JCQ/JCQ-facility-1900x800_locker.jpg",
    ],
    phone: "(028) 7309 6660",
    title_small: "TIỆN NGHI",
    infor: [
      "Studio Yoga",
      "Khu vực tập chức năng",
      "Dụng cụ hỗ trợ",
      "Máy tập nhập khẩu",
      "Phòng xông hơi ướt/khô",
      "Gian hàng thời trang",
      "Quầy bar Lounge ép lạnh",
      "Tủ khoá rộng lớn",
      "Bàn trang điểm",
      "Máy sấy tóc",
    ],
  },
  {
    title: "JVJ - California Active Trường Sơn - Q.Tân Bình",
    name: "CALIFORNIA ACTIVE - VIETJET PLAZA, QUẬN TÂN BÌNH",
    city: "Hồ Chí Minh",
    ward: "Phường 2",
    district: "Quận Tân Bình",
    street: "Vietjet Plaza, 60A Trường Sơn",
    desc: [
      "Trẻ trung, dễ tiếp cận và tập theo cách bạn muốn. California Active hướng đến trải nghiệm tập luyện dành cho tất cả mọi người muốn một phòng gym tiêu chuẩn quốc tế ngay nơi mình sống và dễ dàng đến luyện tập nhanh hơn bao giờ hết.",
      "Trẻ trung, dễ tiếp cận và tập theo cách bạn muốn. California Active hướng đến trải nghiệm tập luyện dành cho tất cả mọi người muốn một phòng gym tiêu chuẩn quốc tế ngay nơi mình sống và dễ dàng đến luyện tập nhanh hơn bao giờ hết.",
      "Toạ lạc tại Vietjet Plaza, 60A Trường Sơn gần khu dân cư cao cấp với không gian Yoga ấm cúng, chương trình Yoga đa dạng và độc nhất Đông Nam Á, Yoga Plus Thảo Điền quận 2 chính là thiên đường Yoga đích thực dành cho các hội viên yêu thích trải nghiệm Yoga chuyên sâu.",
    ],
    times_days: [
      {
        time: "6:00 - 23:00",
        day: "Thứ 2 - Thứ 6",
      },
      {
        time: "8:00 - 22:00",
        day: "Thứ 7, CN",
      },
    ],
    img: [
      "https://cali.vn/storage/app/media/2022/Club/JVJ/JVJ_Thumbnail.jpg",
      "https://cali.vn/storage/app/media/2022/Club/JVJ/CA_Vietjet_facade_1900x800.jpg",
      "https://cali.vn/storage/app/media/2022/Club/JCQ/JCQ-facility-1900x800_studio.jpg",
      "https://cali.vn/storage/app/media/2022/Club/JVJ/CA_Vietjet_treadmil_1900x800.jpg",
      "https://cali.vn/storage/app/media/2022/Club/JCQ/JCQ-facility-1900x800_locker.jpg",
    ],
    phone: "(028) 7105 8989",
    title_small: "TIỆN NGHI",
    infor: [
      "Studio Yoga",
      "Khu vực tập chức năng",
      "Dụng cụ hỗ trợ",
      "Máy tập nhập khẩu",
      "Phòng xông hơi ướt/khô",
      "Gian hàng thời trang",
      "Quầy bar Lounge ép lạnh",
      "Tủ khoá rộng lớn",
      "Bàn trang điểm",
      "Máy sấy tóc",
    ],
  },
];

